version: "3.8" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  database: # 서비스 명
    image: mysql:8 # 사용할 이미지
    container_name: mysql
    environment: # -e 옵션
      MYSQL_DATABASE: instagram
      MYSQL_ROOT_PASSWORD: 1234  # MYSQL 패스워드 설정 옵션
    ports:
      - 3306:3306 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306

  backend:
    image: instagram33/spring
    container_name: spring
    ports:
      - 8080:8080
    depends_on:
      - database # mysql 컨테이너가 실행된 후, spring 컨테이너가 실행
    restart: on-failure

  frontend:
    image: instagram33/react
    container_name: react
    ports:
    - 80:80
    depends_on:
      - backend # spring 컨테이너가 실행된 후, react 컨테이너가 실행